cwl_workflow_class:
  title: Common Workflow Language
  key: cwl
  extractor: CWL
  alternate_name: CWL
  identifier: https://w3id.org/cwl/v1.0/
  url: https://www.commonwl.org/

galaxy_workflow_class:
  title: Galaxy
  key: galaxy
  extractor: Galaxy
  identifier: https://galaxyproject.org/
  url: https://galaxyproject.org/

knime_workflow_class:
  title: KNIME
  key: knime
  extractor: KNIME
  identifier: https://www.knime.com/
  url: https://www.knime.com/

nextflow_class:
  title: Nextflow
  key: nextflow
  extractor: Nextflow
  identifier: https://www.nextflow.io/
  url: https://www.nextflow.io/

snakemake_class:
  title: Snakemake
  key: snakemake
  extractor: Snakemake
  identifier: https://doi.org/10.1093/bioinformatics/bts480
  url: https://snakemake.readthedocs.io
