#MySQL

default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: 5
  username: mysqluser
  password: mysqlpassword

development:
  <<: *default
  database: seek_development

test:
  <<: *default
  database: seek_test

production:
  <<: *default
  database: seek_production
